### ISSUE TITLE
Cant deploy using deploy.rb because of deploy rights

### ISSUE THREAD

**Issue by emilebosch** [slickage/ansible-rails#2]
Because a user with the rights deploy is made, capisrano isnt able  to create another directory structure. 

```
cannot create directory '/data/cap/releases'
```

Am i missing something?

**Comment by wangbus** [comment]
No, you're right. Thanks for the heads up!

**Comment by bbraga** [comment]
Just make sure you edit the file _roles/webserver/tasks/deploy.rb_, to match your public key:

``` yaml
- authorized_key: user=deploy key="{{ lookup('file', '/home/<user>/.ssh/id_rsa.pub') }}"
```

Afterwards make sure your Cap deploy.rb file uses :user => 'deploy'
